POST https://www.solicitors.com/prepare-search.asp HTTP/1.1
host: www.solicitors.com
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
accept-language: en-GB,en-US;q=0.9,en;q=0.8
cache-control: max-age=0
content-type: application/x-www-form-urlencoded
dnt: 1
origin: https://www.solicitors.com
priority: u=0, i
referer: https://www.solicitors.com/
sec-ch-ua: "Chromium";v="148", "Microsoft Edge";v="148", "Not/A)Brand";v="99"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36 Edg/148.0.0.0
cookie: ASPSESSIONIDAAATBQTC=FCHHGBKDNIAFLJMJEOGDIOAI; _gid=GA1.2.936520853.1780498105; _ga=GA1.2.940262719.1780498105; _ga_BR4J80BNZL=GS2.1.s1780498105$o1$g1$t1780498679$j60$l0$h0
content-length: 38

did=Select+area+of+law&location=London